const chuck = { "_id": "5e2a30011c9d4400007d0d98", "name": "Chucky", "health": 80, "currentHealth": 80, "attack": 40, "defense": 60, "speed": 70, "movespool": [{ "name": "Pistol-Whip", "strength": 10, "effect": 1, "animation": "heavyAttack", "hit": "crossSlash" }, { "name": "Rapid Shank", "strength": 18, "effect": 0, "animation": "multiAttack", "hit": "multiSlash" }, { "name": "Tackle", "strength": 4, "effect": 3, "animation": "attack", "hit": "strike" }, { "name": "Stuffed Cottons", "strength": 6, "effect": 3, "animation": "attack", "hit": "explosion" }], "imageUrl": "https://res.cloudinary.com/df6rrvdqm/image/upload/v1579894619/monster-mayhem/chuckie-standard-size_gyxw9z.png", "animations": { "base": "./images/animations/chucky/stand/chucky_1-1", "attack": { "path": "./images/animations/chucky/stab/chucky_8-", "frames": 10 }, "heavyAttack": { "path": "./images/animations/chucky/roundhouse-slash/chucky_12-", "frames": 10 }, "death": { "path": "./images/animations/chucky/death/chucky_5-", "frames": 5 }, "idle": { "path": "./images/animations/chucky/stand/chucky_1-", "frames": 12 }, "multiAttack": { "path": "./images/animations/chucky/multi-stab/chucky_8-", "frames": "18" }, "filetype": ".png" }, "__v": 0 }
const fred = { "_id": "5e2a301c1c9d4400007d0d99", "name": "Freddy Kreuger", "health": 110, "currentHealth": 110, "attack": 60, "defense": 40, "speed": 50, "movespool": [{ "name": "Poison Claw", "strength": 4, "effect": 2, "animation": "attack", "hit": "crossSlash" }, { "name": "Fury Swipes", "strength": 15, "effect": 0, "animation": "combo", "hit": "multiSlash" }, { "name": "Tackle", "strength": 4, "effect": 3, "animation": "kick", "hit": "strike" }, { "name": "Iron Shank", "strength": 6, "effect": 4, "animation": "heavyKick", "hit": "crossSlash" }], "imageUrl": "https://res.cloudinary.com/df6rrvdqm/image/upload/v1579894619/monster-mayhem/freddy-standard-size_tzktji.png", "animations": { "base": "./images/animations/freddy/idle/freddy_0-0", "kick": { "path": "./images/animations/freddy/kick/freddy_210-", "frames": 47 }, "heavyKick": { "path": "./images/animations/freddy/roundhouse/freddy_240-", "frames": 27 }, "knee": { "path": "./images/animations/freddy/knee/freddy_220-", "frames": 14 }, "attack": { "path": "./images/animations/freddy/combo/freddy_200-", "frames": 30 }, "combo": { "path": "./images/animations/freddy/combo/freddy_200-", "frames": "74" }, "death": { "path": "./images/animations/freddy/death/freddy_255-", "frames": 12 }, "idle": { "path": "./images/animations/freddy/idle/freddy_0-", "frames": 45 }, "filetype": ".png" }, "__v": 0 }
const jason = { "_id": "5e2a30551c9d4400007d0d9b", "name": "Jason Voorhees", "health": 110, "currentHealth": 110, "attack": 40, "defense": 60, "speed": 30, "movespool": [{ "name": "Claw Hammer", "strength": 8, "effect": 4, "animation": "heavyAttack", "hit": "crossSlash" }, { "name": "Tackle", "strength": 4, "effect": 3, "animation": "punch", "hit": "strike" }, { "name": "Machete Strike", "strength": 20, "effect": 0, "animation": "superHeavyAttack", "hit": "crossSlash" }, { "name": "Poison Flare", "strength": 0, "effect": 2, "animation": "attack", "hit": "poisonBlast" }], "imageUrl": "https://res.cloudinary.com/df6rrvdqm/image/upload/v1579894619/monster-mayhem/jason-standard-size_qt5bvx.png", "animations": { "base": "./images/animations/jason/stand/jason_0-0", "attack": { "path": "./images/animations/jason/slash/jason_200-", "frames": 13 }, "heavyAttack": { "path": "./images/animations/jason/heavy-slash/jason_610-", "frames": 17 }, "punch": { "path": "./images/animations/jason/punch/jason_230-", "frames": 7 }, "superHeavyAttack": { "path": "./images/animations/jason/chop/jason_210-", "frames": 16 }, "range": { "path": "./images/animations/jason/bow/jason_1200-", "frames": 13 }, "death": { "path": "./images/animations/jason/death/jason_5950-", "frames": 16 }, "idle": { "path": "./images/animations/jason/stand/jason_0-", "frames": 14 }, "filetype": ".png" }, "__v": 0 }
const pen = { "_id": "5e2cf05c1c9d440000b08573", "name": "Pennywise", "health": 100, "currentHealth": 100, "attack": 50, "defense": 50, "speed": 40, "movespool": [{ "name": "Balloon Explosion", "strength": 12, "effect": 1, "animation": "dance", "hit": "explosion" }, { "name": "Poison Powder", "strength": 0, "effect": 2, "animation": "attack", "hit": "poisonBlast" }, { "name": "Nail Spikes", "strength": 0, "effect": 4, "animation": "kick", "hit": "crossSlash" }, { "name": "Tackle", "strength": 4, "effect": 3, "animation": "heavyAttack", "hit": "strike" }], "imageUrl": "https://res.cloudinary.com/df6rrvdqm/image/upload/v1579894619/monster-mayhem/penny-standard-size_o4itkk.png", "animations": { "base": "./images/animations/penny/stand/penny_0-0", "attack": { "path": "./images/animations/penny/punch/penny_100-", "frames": 5 }, "heavyAttack": { "path": "./images/animations/penny/heavy-punch/penny_200-", "frames": 4 }, "kick": { "path": "./images/animations/penny/kick/penny_230-", "frames": 6 }, "dance": { "path": "./images/animations/penny/dance/penny_181-", "frames": 4 }, "death": { "path": "./images/animations/penny/death/penny_440-", "frames": 9 }, "idle": { "path": "./images/animations/penny/stand/penny_0-", "frames": 7 }, "filetype": ".png" }, "__v": 0 }

export const monsters = {
  [chuck._id]: chuck,
  [fred._id]: fred,
  [jason._id]: jason,
  [pen._id]: pen
}

